services:
  - type: web
    name: trypost
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: TryPost
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: SELF_HOSTED
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: trypost
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.cafvchvvlcfugjgmurya
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          name: trypost-redis
          type: keyvalue
          property: connectionString
      - key: QUEUE_CONNECTION
        value: redis
      - key: CACHE_STORE
        value: redis
      - key: SESSION_DRIVER
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: TIKTOK_CLIENT_ID
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_CLIENT_REDIRECT
        value: "${APP_URL}/accounts/tiktok/callback"
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_REDIRECT
        value: "${APP_URL}/accounts/facebook/callback"
      - key: PASSPORT_PRIVATE_KEY
        sync: false
      - key: PASSPORT_PUBLIC_KEY
        sync: false
